spring:
  datasource:
    url: jdbc
    username: root
    password: root123
    deriver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181